<?php defined('SYSPATH') or die('No direct access allowed.');

return array(
    'genders' => array(
        1 => 'Man',
        2 => 'Vrouw',
    ),

    'child_genders' => array(
        1 => 'Jongen',
        2 => 'Meisje',
    ),

    'author_types' => array(
        'mother' => 'Mama Blogger',
        'expert' => 'Expert Blogger',
    ),

    'item_types' => array(
        'post' => 'Blog',
        'post_short' => 'Vraag',
        'post_picture' => 'Foto Blog',
        'post_video' => 'Video Blog',
        'comment' => 'Reactie',
        'tipwin' => 'Tip & Win',
        'follower' => 'Volger',
    ),

    'subscription_groups' => array(
        'Win' => 'Win',
        'Testpanels' => 'Testpanels',
        'Voordeelclub' => 'Voordeelclub',
        'Blog / Advies' => 'Blog / Advies',
        'Partner Aanbieding' => 'Partner Aanbieding',
    ),

    'blog_types' => array(
        'post' => 'Blog',
        'post_short' => 'Vraag',
        'post_picture' => 'Foto Blog',
        'post_video' => 'Video Blog',
    ),

    'registration_panels' => array(
        'default' => array(
            'title' => 'Mamaplaats Dé Blogsite voor en door moeders!',
            'subtitle' => 'Registreer je bij Mamaplaats en mis niets!',
        ),
        'CenA' => array(
            'title' => 'Win €450,- aan gratis shoppen bij C&A!',
            'subtitle' => '2de prijs = €200,- 3de prijs = €100,-',
        ),
        'Testmoeders' => array(
            'title' => 'Mamaplaats zoekt testmoeders voor unieke producten!',
            'subtitle' => 'Registreer en schrijf je in!',
        ),
    ),

    'pregnancy_calendar' => array(
        '1-week-zwanger' => 'advies/1-week-zwanger/',
        '2-weken-zwanger' => 'advies/2-weken-zwanger/',
        '3-weken-zwanger' => 'advies/3-weken-zwanger/',
        '4-weken-zwanger' => 'advies/4-weken-zwanger/',
        '5-weken-zwanger' => 'advies/5-weken-zwanger/',
        '6-weken-zwanger' => 'advies/6-weken-zwanger/',
        '7-weken-zwanger' => 'advies/7-weken-zwanger/',
        '8-weken-zwanger' => 'advies/8-weken-zwanger/',
        '9-weken-zwanger' => 'advies/9-weken-zwanger/',
        '10-weken-zwanger' => 'advies/10-weken-zwanger/',
        '11-weken-zwanger' => 'advies/11-weken-zwanger/',
        '12-weken-zwanger' => 'advies/12-weken-zwanger/',
        '13-weken-zwanger' => 'advies/13-weken-zwanger/',
        '14-weken-zwanger' => 'advies/14-weken-zwanger/',
        '15-weken-zwanger' => 'advies/15-weken-zwanger/',
        '16-weken-zwanger' => 'advies/16-weken-zwanger/',
        '17-weken-zwanger' => 'advies/17-weken-zwanger/',
        '18-weken-zwanger' => 'advies/18-weken-zwanger/',
        '19-weken-zwanger' => 'advies/19-weken-zwanger/',
        '20-weken-zwanger' => 'advies/20-weken-zwanger/',
        '21-weken-zwanger' => 'advies/21-weken-zwanger/',
        '22-weken-zwanger' => 'advies/22-weken-zwanger/',
        '23-weken-zwanger' => 'advies/23-weken-zwanger/',
        '24-weken-zwanger' => 'advies/24-weken-zwanger/',
        '25-weken-zwanger' => 'advies/25-weken-zwanger/',
        '26-weken-zwanger' => 'advies/26-weken-zwanger/',
        '27-weken-zwanger' => 'advies/27-weken-zwanger/',
        '28-weken-zwanger' => 'advies/28-weken-zwanger/',
        '29-weken-zwanger' => 'advies/29-weken-zwanger/',
        '30-weken-zwanger' => 'advies/30-weken-zwanger/',
        '31-weken-zwanger' => 'advies/31-weken-zwanger/',
        '32-weken-zwanger' => 'advies/32-weken-zwanger/',
        '33-weken-zwanger' => 'advies/33-weken-zwanger/',
        '34-weken-zwanger' => 'advies/34-weken-zwanger/',
        '35-weken-zwanger' => 'advies/35-weken-zwanger/',
        '36-weken-zwanger' => 'advies/36-weken-zwanger/',
        '37-weken-zwanger' => 'advies/37-weken-zwanger/',
        '38-weken-zwanger' => 'advies/38-weken-zwanger/',
        '39-weken-zwanger' => 'advies/39-weken-zwanger/',
        '40-weken-zwanger' => 'advies/40-weken-zwanger/',
        '41-weken-zwanger' => 'advies/41-weken-zwanger/',
        '42-weken-zwanger' => 'advies/42-weken-zwanger/',
    ),

    'after_birth_calendar' => array(
        'baby-1-week' => 'advies/baby-1-week/',
        'baby-2-weken' => 'blog/baby-2-weken/',
        'baby-3-weken' => 'blog/baby-3-weken/',
        'baby-4-weken' => 'blog/baby-4-weken/',
        'baby-5-weken' => 'blog/baby-5-weken/',
        'baby-6-weken' => 'blog/baby-6-weken/',
        'baby-7-weken' => 'blog/baby-7-weken/',
        'baby-8-weken' => 'blog/baby-8-weken/',
        'baby-9-weken' => 'blog/baby-9-weken/',
        'baby-10-weken' => 'blog/baby-10-weken/',
        'baby-11-weken' => 'blog/baby-11-weken/',
        'baby-12-weken' => 'blog/baby-12-weken/',
        'baby-13-weken' => 'blog/baby-13-weken/',
        'baby-14-weken' => 'blog/baby-14-weken/',
        'baby-4-maanden' => 'blog/baby-4-maanden/',
        'baby-5-maanden' => 'blog/baby-5-maanden/',
        'baby-6-maanden' => 'blog/baby-6-maanden/',
        'baby-7-maanden' => 'blog/baby-7-maanden/',
        'baby-8-maanden' => 'blog/baby-8-maanden/',
        'baby-9-maanden' => 'blog/baby-9-maanden/',
        'baby-10-maanden' => 'blog/baby-10-maanden/',
        'baby-11-maanden' => 'blog/baby-11-maanden/',
        'peuter-12-maanden' => 'blog/peuter-12-maanden/',
        'peuter-18-maanden' => 'blog/peuter-18-maanden/',
        'kleuter-24-maanden' => 'blog/kleuter-24-maanden/',
        'kleuter-30-maanden' => 'blog/kleuter-30-maanden/',
        'kleuter-3-jaar' => 'blog/kleuter-3-jaar/',
        'kleuter-3,5-jaar' => 'advies/kleuter-35-jaar/',
        'kleuter-4-jaar' => 'blog/kleuter-4-jaar/',
        'kleuter-4,5-jaar' => 'advies/kleuter-45-jaar/',
        'kind-5-jaar' => 'blog/kind-5-jaar/',
        'kind-6-jaar' => 'blog/kind-6-jaar/',
        'kind-7-jaar' => 'blog/kind-7-jaar/',
        'kind-8-jaar' => 'blog/kind-8-jaar/',
    ),

    'conversation_query_params' => array(
        'draft' => 'draft',
        'unread' => 'unread',
        'deleted' => 'deleted',
        'inbox' => 'inbox',
        'outbox' => 'outbox'
    ),
);