<?php defined('SYSPATH') OR die('No direct script access.');

class Migration_Core_20140217093848 extends Minion_Migration_Base {

	/**
	 * Run queries needed to apply this migration
	 *
	 * @param Kohana_Database $db Database connection
	 */
	public function up(Kohana_Database $db)
	{
		$review_remarks = array(
			array(78,"positive","apparaat slaat vanzelf af"),
			array(78,"positive","Altijd juiste hoeveelheid"),
			array(78,"positive","Pure, malse en lekkere smaak"),
			array(78,"positive","Apparaat slaat vanzelf af"),
			array(78,"positive","makkelijk, gebruiksvriendelijk apparaat"),
			array(78,"positive","Makkelijk schoon te maken"),
			array(78,"negative","Deksel sluiten is lastig"),
			array(78,"negative","Klein voor grotere eters"),
			array(78,"negative","Maatbeker mag groter zijn"),
			array(120,"positive","Spelletjes met eigen foto"),
			array(120,"positive","Makkelik in gebruik voor kids"),
			array(120,"positive","Makkelijk te bewerken"),
			array(501,"positive","Heldere duidelijke stem"),
			array(501,"positive","Veel verschillende liedjes"),
			array(501,"positive","Herkenbare liedjes"),
			array(501,"positive","Beschermhoesje en 2 pennen erbij"),
			array(501,"positive","Media van je Storio2 op pc zetten"),
			array(501,"negative","Lang laden bij elke stap"),
			array(501,"negative","Sommige liedjes zijn erg kort"),
			array(501,"negative","Lastig om een icoontje goed aan te klikken"),
			array(586,"positive","Je hoeft niet op de tijd te letten"),
			array(586,"positive","Heerlijk van smaak"),
			array(586,"positive","Aan 2 kanten koken; scheelt pannen"),
			array(586,"positive","Smaak van groenten blijft goed bewaard"),
			array(586,"positive","Makkelijk schoon te maken"),
			array(586,"positive","Veilig voor kinderen"),
			array(586,"negative","Deeg van de pannenkoeken waren slapjes"),
			array(586,"negative","Sommige recepten leken niet te kloppen"),
			array(872,"positive","Makkelijk te installeren"),
			array(872,"positive","Leuke geluidjes"),
			array(872,"positive","Leuke schuifpuzzel onder de tafel"),
			array(872,"positive","Snel klaar voor gebruik"),
			array(872,"negative","Uitleg duurde iets te lang"),
			array(872,"negative","Kind moet oud genoeg zijn voor tablet"),
			array(882,"positive","Veel mogelijkheden"),
			array(882,"positive","Incl. USB aansluiting"),
			array(882,"positive","Gebruiksvriendelijk voor kids"),
			array(882,"positive","Makkelijk om mee te nemen"),
			array(882,"negative","Er zit geen hoesje omheen"),
			array(882,"negative","Kwaliteit foto's niet altijd goed"),
			array(938,"positive","Makkelijk in elkaar te zetten"),
			array(938,"positive","Leuke muziekjes"),
			array(938,"positive","Leerzame spelletjes"),
			array(938,"positive","Stuurtje en piano kun je echt bedienen"),
			array(938,"positive","Leuke puzzel"),
			array(938,"negative","Te jong voor de tablet"),
			array(938,"negative","Spelletjes ietwat moeilijk"),
			array(1346,"positive","Heel kindvriendelijk"),
			array(1346,"positive","Je kunt de lens omdraaien"),
			array(1346,"positive","Meerdere profielen aan te maken"),
			array(1346,"positive","Incl. USB kabeltje"),
			array(1346,"positive","Bekende kleuterverhalen"),
			array(1346,"positive","Duidelijke uitleg"),
			array(1346,"positive","Leerzaam"),
			array(1346,"negative","Sommige spellen te kinderachtig "),
			array(1346,"negative","Batterijen zijn heel snel leeg"),
			array(1346,"negative","Laden duurt soms wat lang"),
			array(1899,"positive","Compacte wagen"),
			array(1899,"positive","Makkelijk te monteren"),
			array(1899,"positive","Ruime boodschappenmand"),
			array(1899,"positive","Makkelijk sturen"),
			array(1899,"positive","Fijne rem"),
			array(1899,"positive","Matrasje van goede kwaliteit"),
			array(1899,"negative","Aan de kleine kant"),
			array(1899,"negative","Geen verstelbare vering"),
			array(1899,"negative","Wagen is ietwat stijfjes "),
			array(2068,"positive","Makkelijk om te winkelen"),
			array(2068,"positive","Verschillende standen"),
			array(2068,"positive","Makkelijk in elkaar te klappen"),
			array(2068,"positive","Rijdt heel soepel"),
			array(2068,"positive","Makkelijk een duo wagen van te maken"),
			array(2068,"positive","Past goed in kofferbak"),
			array(2068,"negative","Geen tasbevestiging"),
			array(2068,"negative","Weinig opslagruimte met 2 kids"),
			array(2560,"positive","Verrasingspakket "),
			array(2560,"positive","Gezond, lekker en voedzaam "),
			array(2560,"positive","Mileuvriendelijk "),
			array(2560,"positive","Goede en gebruiksvriendelijke recepten"),
			array(2560,"positive","Praktisch: je hoeft niet zelf na te denken wat je gaat eten "),
			array(2560,"negative","Geen aanpassing op de recepten voor kinderen"),
			array(3012,"positive","Vers en lekker"),
			array(3012,"positive","Alle producten zijn mee geleverd"),
			array(3012,"negative","Veel voorbereidingstijd"),
			array(3012,"negative","Porties zijn erg groot waardoor we veel over houden"),
			array(3012,"positive","Erg lekker ook voor kinderen"),
			array(3032,"positive","Lekker en gezond"),
			array(3032,"positive","Praktisch en handig"),
			array(3032,"positive","Pakket is compleet, extra boodschappen doen is niet nodig"),
			array(3032,"positive","Perfecte grootte van de porties"),
			array(3032,"negative","Lange bereidingstijd"),
			array(3032,"negative","De prijs "),
			array(2144,"positive","Makkelijk uit te drinken"),
			array(2144,"positive","Goed schoon te krijgen"),
			array(2144,"positive","Lekt niet"),
			array(2144,"positive","Te grbuiken als gewone beker"),
			array(2144,"positive","Beker kan warmhouden"),
			array(2144,"negative","Kan niet in de vaatwasser"),
			array(2144,"negative","Goed dichtdraaien om niet te lekken"),
			array(2156,"positive","Lekt niet"),
			array(2156,"positive","Stevige beker"),
			array(2156,"positive","Kan tegen een stootje"),
			array(2156,"positive","Geen losse onderdelen"),
			array(2156,"negative","Kan niet in vaatwasser"),
			array(2156,"negative","Hard zuigen om te drinken"),
			array(2156,"negative","Geen handvat of extra grip"),
			array(2157,"positive","Makkelijk uit te drinken"),
			array(2157,"positive","Lekt niet"),
			array(2157,"positive","Eén geheel"),
			array(2157,"positive","Kan niet in de vaatwasser"),
			array(2157,"positive","Fijne, grote handvaten"),
			array(2157,"positive","Fijn voor kinderhandjes"),
			array(2157,"negative","Je kunt de beker niet goed dichtdraaien"),
			array(2157,"negative","Zachte tuit krijg je niet makkelijk schoon"),
			array(2157,"negative","Handvaten zijn erg lang"),
			array(3128,"positive","Lekker en gezond"),
			array(3128,"positive","Sommige producten zijn biologisch"),
			array(3128,"positive","Thuis bezorgd"),
			array(3128,"negative ","Er wordt (behalve Veggie) geen rekening gehouden met dieetwensen"),
			array(3128,"positive","Handige recepten "),
			array(3173,"positive","Verrassingspaket"),
			array(3173,"positive","Bijzondere en verse producten "),
			array(3173,"positive","Gevarieerde recepten "),
			array(3173,"negative ","Langere bereidingstijd dan aangegeven "),
			array(3564,"positive","Ruime keuze uit lijsten "),
			array(3564,"negative ","Beperkte keuze uit kleuren "),
			array(3564,"negative ","Je kunt niet via iPad bestellen "),
			array(3564,"negative ","Prijzig"),
			array(3564,"positive","Gebruiksvriendelijk en snel "),
			array(3564,"positive","Persoonlijk en mooi cadeau "),
			array(3566,"positive","Snelle service"),
			array(3566,"positive","Mooi verpakt"),
			array(3566,"positive","Mooie kwaliteit"),
			array(3566,"negative ","Bewerken van de foto's werkte traag"),
			array(3566,"negative ","Niet alle lijsten op voorraad"),
			array(2160,"positive","Mooie beker!"),
			array(2160,"positive","Makkelijk vast te houden"),
			array(2160,"positive","Weinig krachtig nodig om te drinken"),
			array(2160,"positive","Lekt niet"),
			array(2160,"positive","Hygiënisch"),
			array(2160,"positive","Weinig onderdelen"),
			array(2160,"negative ","Smalle handvaten"),
			array(2160,"negative ","Lastig dicht te draaien door handvaten"),
			array(2175,"positive","Echt anti-lek!"),
			array(2175,"positive","Aantrekkelijk, vrolijk design"),
			array(2175,"positive","Goed vast te houden"),
			array(2175,"positive","Makkelijk uit te drinken"),
			array(2175,"negative ","Ietwat aan de grote kant"),
			array(2175,"negative ","Ondoorzichtig"),
			array(2229,"positive","Makkelijk schoon te maken"),
			array(2229,"positive","Anti-lek"),
			array(2229,"positive","Stevige beker"),
			array(2229,"positive","Goed vast te pakken"),
			array(2229,"positive","Leuk design"),
			array(2229,"negative ","Geen nadelen!"),
			array(2232,"positive","Makkelijk schoon te maken"),
			array(2232,"positive","Je hoeft niet hard te zuigen"),
			array(2232,"positive","Lekt niet"),
			array(2232,"positive","Goed vast te houden"),
			array(2232,"positive","Leuke afbeeldingen"),
			array(2232,"negative ","Kan niet in vaatwasser"),
			array(2240,"positive","Mooie kleuren"),
			array(2240,"positive","Makkelijk vast te houden"),
			array(2240,"positive","Niet te zwaar"),
			array(2240,"negative ","De beker lekt"),
			array(2240,"negative ","Materiaal scheurt"),
			array(2254,"positive","Makkelijk schoon te maken"),
			array(2254,"positive","Makkelijk vast te pakken"),
			array(2254,"positive","Lekt niet"),
			array(2254,"positive","Fijne handgrepen"),
			array(2254,"positive","De zachte tuit is erg fijn"),
			array(2254,"negative ","Geen nadelen!"),
			array(2304,"positive","Kan tegen een stootje"),
			array(2304,"positive","Lichte beker"),
			array(2304,"positive","Makkelijk vast te pakken"),
			array(2304,"positive","Vrolijke beker"),
			array(2304,"positive","Makkelijk schoon te maken"),
			array(2304,"positive","Drinken blijft lang warm"),
			array(2304,"negative ","Lekt als je ermee schud"),
			array(2304,"negative ","Kan niet in de vaatwasser"),
			array(2356,"positive","Mooi, vrolijk design"),
			array(2356,"positive","Beker lekt niet"),
			array(2356,"positive","Makkelijk uit te drinken"),
			array(2356,"positive","Makkelijk vast te houden"),
			array(2356,"negative ","Beker is aan de grote kant"),
			array(2356,"negative ","Beker is ondoorzichtig"),
			array(2356,"negative ","niet met één hand te dragen"),
			array(2483,"positive","Mooie kleuren"),
			array(2483,"positive","Zachte tuit is erg fijn"),
			array(2483,"positive","Fijne handgrepen"),
			array(2483,"positive","Makkelijk uit te drinken"),
			array(2483,"positive","Vrolijkp laatje op de beker"),
			array(2483,"positive","Luchtvrij"),
			array(2483,"negative ","Lekt een beetje"),
			array(2483,"negative ","Lastig dicht te draaien"),
			array(2483,"negative ","De dop past niet meer goed"),
			array(3665,"positive","Makkelijk en leuk "),
			array(3665,"positive","Prijs "),
			array(3665,"negative","Afhankelijk van bezorging "),
			array(3665,"negative","Schrijven op tablet is lastig "),
			array(3700,"positive","Snelle bezorging "),
			array(3700,"positive","Bestellen en betalen verloopt vlot "),
			array(3700,"negative","Keuze qua lijstjes en formaten is niet zo ruim "),
			array(3700,"negative","Draaien en plaatsen van de foto ging vrij lastig"),
			array(3754,"positive","Leuk om te doen!"),
			array(3754,"positive","Persoonlijke touch aan een kaartje"),
			array(3754,"negative","Schrijven van een tekst is vrij lastig "),
			array(3754,"positive","Grote keuze uit verschillende kaartjes "),
			array(3754,"positive","Enthousiaste reacties van de ontvangers"),
			array(2762,"positive","Drinken bleef goed warm"),
			array(2762,"positive","Gaat niet stollen o.i.d."),
			array(2762,"positive","Erg fijn om mee te nemen"),
			array(2762,"positive","Afmetingen staan in de fles"),
			array(2762,"positive","Leuke kleuren"),
			array(2762,"negative","Fles is vrij zwaar"),
			array(3320,"positive","Voeding stroomt niet te snel"),
			array(3320,"positive","Je krijgt niet veel lucht binnen"),
			array(3320,"positive","Makkelijk om mee te nemen"),
			array(3320,"positive","Fles ziet er erg leuk uit"),
			array(3320,"positive","Voeding blijft goed warm"),
			array(3320,"positive","Voeding blijft niet al te lang warm"),
		);

		foreach ($review_remarks as $review_remark)
		{
			$review_id = $review_remark[0];
			$remark_type = $review_remark[1];
			$remark = $review_remark[2];

			// Also add the advise category
			$db->query(Database::UPDATE, "
				INSERT INTO review_remarks (review_id, type, remark)
				VALUES (".$review_id.", '".$remark_type."', ".$db->escape($remark).")
			");
		}
	}

	/**
	 * Run queries needed to remove this migration
	 *
	 * @param Kohana_Database $db Database connection
	 */
	public function down(Kohana_Database $db)
	{
		// $db->query(NULL, 'DROP TABLE ... ');
	}

}
